Repository Nw84/KinoNextJS, pull requests merged in 2022-05, with the labels that each got.

#43 add styling for aboutUs navbar and added styling for active link on mainNavbar
  components/layout/AboutUsNavigation.js
  components/layout/AboutUsNavigation.module.css
  components/layout/MainNavigation.js
  components/layout/MainNavigation.module.css
Labels: AboutUS

#42 Added some style for spec movie-page
  components/movies/MovieDetails.js
  components/movies/MovieDetails.module.css
Labels: SpecMovie

#46 Footer2
  components/layout/Footer.js
  components/layout/Footer.module.css
  components/layout/Layout.js
  components/layout/Layout.module.css
  public/facebook-logo.png
  public/instagram-logo.png
  public/twitter-logo.png
  styles/globals.css
Labels: good first issue

#47 Get reviews
  components/reviews/ReviewItem.js
  components/reviews/ReviewItem.module.css
  components/reviews/ReviewList.js
  components/reviews/ReviewList.module.css
  helpers/getReviews.js
  pages/movies/[movieID]/index.js
Labels: DB

#49 New db
  components/movies/PosterItem.js
  components/movies/PosterList.js
  components/reviews/ReviewForm.js
  components/reviews/ReviewForm.module.css
  components/reviews/ReviewList.js
  components/reviews/ReviewList.module.css
  components/screenings/ScreeningItem.js
  components/screenings/ScreeningsList.js
  helpers/getAllPosters.js
  helpers/getReviews.js
  helpers/getScreenings.js
  helpers/getUser.js
  helpers/posterHelper.js
  helpers/reviewHelper.js
  helpers/screeningHelper.js
  helpers/userHelper.js
  pages/api/login.js
  pages/api/review.js
  pages/api/users.js
  pages/index.js
  pages/login/index.js
  pages/movies/[movieID]/index.js
  pages/movies/index.js
  pages/tickets/[...slug].js
  pages/tickets/index.js
  styles/movieId.module.css
Labels: DB

#54 added movieposters on moviepage with styling, added one more movie in…
  components/layout/MainHero.js
  components/layout/MainHero.module.css
  components/movies/MovieLink.js
  components/movies/MovieLink.module.css
  components/movies/MovieList.js
  components/movies/MovieList.module.css
  pages/movies/index.js
  styles/movies.module.css
  styles/movies.modules.css
Labels: MoviePage

#59 Login style
  components/layout/MainNavigation.js
  components/login/LoginForm.js
  components/login/LoginForm.module.css
  components/login/RegistrationForm.js
  components/login/RegistrationForm.module.css
  components/ui/Button.module.css
  pages/api/login.js
  pages/api/users.js
  pages/login/index.js
  styles/login.module.css
Labels: Account
